### ISSUE TITLE
Save multiple ROIs into tif file

### ISSUE THREAD

**Issue by ericsua** [cgohlke/roifile#10]
I saw that it is possible to save ROIs individually in different files or together in a single zip file. This package is also able to decode multiple ROIs contained in a tif file created with ImageJ, but I can't find a way to encode multiple ROIs in one tif file. Is there a way to save multiple ROIs into a single tif file?

**Comment by cgohlke** [comment]
Does using a sequence of ImagejRoi not work for you? For example:

https://github.com/cgohlke/roifile/blob/c966c36777d4974a93257f03e49046d4b300e1a8/roifile_demo.py#L49-L57

**Comment by ericsua** [comment]
Yes! That solved my problem. I looked over all the code of the package but I didn't see that demo file. Thank you.

**Comment by cgohlke** [comment]
There should probably be a little example for reading/writing TIFF in the main docstring.

**Comment by ericsua** [comment]
Yes, that would be great. Or maybe you could just add a more explicit reference to the `roifile_demo.py` file in the docstring
