### ISSUE TITLE
Feature suggestion: ImagejRoi.tofile ZIP support for multiple ROIs

### ISSUE THREAD

**Issue by csachs** [cgohlke/roifile#3]
At the moment, a single ROI can be stored in a ZIP file, or the call can be used multiple times to append ROIs into a ZIP file, which is however much slower than directly using `zipfile` to create a ZIP with multiple ROIs in one go. As a feature suggestion, a function to create a ZIP file with a list of ROIs would be very nice.

**Comment by cgohlke** [comment]
It would be awkward to add multi-ROI support to an instance method. This case should be handled in a high level `roiwrite` function. For now use something like (not tested)
```Python
with zipfile.ZipFile(filename, 'w') as zf:
    for roi in roi_list:
        with zf.open(roi.name, 'w') as fh:
            fh.write(roi.tobytes())
```

**Comment by cgohlke** [comment]
In v2020.11.28, use `roiwrite(filename, roi_list)`
