### ISSUE TITLE
roifile_demo.py - FileNotFoundError: [Errno 2] No such file or directory: '\tests\box.tif'

### ISSUE THREAD

**Issue by christianrickert** [cgohlke/roifile#4]
Hello Christoph,

Hope you're doing well!

I've installed `roifile` and wanted to get familiar with its code and features by running the `roifile_demo.py`. It looks like the code is trying to open a missing demo file, i.e. the file [`box.tif`](https://github.com/cgohlke/roifile/blob/45411417138c81ee6893c3e22349eed1f00ff861/roifile_demo.py#L31).

Is the `tests` folder missing or part of another project?'

Best regards,
Chris
```
C:\Users\User\Desktop\roifile-master>roifile_demo.py
Traceback (most recent call last):
  File "C:\Users\User\Desktop\roifile-master\roifile_demo.py", line 31, in <module>
    with TiffFile('tests/box.tif') as tif:
  File "C:\python\lib\site-packages\tifffile\tifffile.py", line 2977, in __init__
    fh = FileHandle(arg, mode=mode, name=name, offset=offset, size=size)
  File "C:\python\lib\site-packages\tifffile\tifffile.py", line 9446, in __init__
    self.open()
  File "C:\python\lib\site-packages\tifffile\tifffile.py", line 9459, in open
    self._fh = open(self._file, self._mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\Desktop\\roifile-master\\tests\\box.tif'
```

**Comment by cgohlke** [comment]
Hi Christian,

the file can be found at https://github.com/csachs/imagej-tiff-meta/tree/example (see also [#1](https://github.com/csachs/imagej-tiff-meta/issues/1)). I'll add a note to the code.

**Comment by christianrickert** [comment]
Thank you very much for the quick response!
