### ISSUE TITLE
Keeping original ROI index

### ISSUE THREAD

**Issue by nal10** [cgohlke/roifile#5]
Hi,

I am loading .roi files from a .zip and modifying them using ImageJRoi.fromfile(). I have noticed that in doing so it is reindexing the files so if you load the modified .zip folder into ImageJ the labels (1-n) are different than the original. It essentially sorts it in the order the .roi files are loaded.

Is there a value within the ImageJRoi object that can be used to identify the files original index value and modified in the new object to maintain the same index?

**Comment by cgohlke** [comment]
Could you provide a file and code to reproduce the issue?
