### ISSUE TITLE
roi.tofile tobyte error with large coordinates

### ISSUE THREAD

**Issue by Bisho2122** [cgohlke/roifile#7]
I have a large image (36000 x 45000) pixels and it's basically a mask of multiple objects. Since the image is big, some of the objects have coordinates bigger than byte mode defined in `struct.pack`. I am a uploading the ".npy" array to reproduce the error. 

`x = 'provided numpy array'
roi = ImageJRoi.frompoints(x)
roi.tofile()`

I hope you can help, because it works for only the objects with max coordinates < 32767. 

Thank you

![image](https://user-images.githubusercontent.com/38420248/158871167-b347c429-870b-40d8-a024-48c183a515f5.png)
[coords.zip](https://github.com/cgohlke/roifile/files/8289223/coords.zip)

**Comment by cgohlke** [comment]
Unfortunately that is a limitation of the ImageJ ROI format.

https://github.com/cgohlke/roifile/blob/a9d59c8b0258722073d6441745455e21e4248e35/roifile/roifile.py#L84-L87

It seems to be a common issue. The `read-roi` library has implemented a [workaround](https://github.com/hadim/read-roi/pull/19), which seem arbitrary.

Is it possible to save ROI file from ImageJ with coordinates > 32767?

**Comment by Bisho2122** [comment]
Oh I didn't know that. However, I do have an ROI set including cells with coordinates larger > 32767. So I am pretty sure that I can save an ROI from ImageJ with coordinates that big. I can probably send an example tomorrow, cause I am currently out of office.

**Comment by cgohlke** [comment]
I see. I didn't realize that you tried to save floating point, not integer, point coordinates. That should work. I'll try to fix that. In that case ImageJ writes bogus/undefined integer coordinates (which are apparently ignored on read) in addition to the subpixel coordinates. For ROI types that do not support floating point coordinates ImageJ writes corrupted files...

**Comment by cgohlke** [comment]
Try floating point coordinates with version 2022.3.18:

```Python
import roifile

roi = roifile.ImagejRoi.frompoints(numpy.load('coords.npy').astype('float32'))
roi.roitype = roifile.ROI_TYPE.POINT
roi.tofile('issue7.roi')
roi.plot()
```

**Comment by Bisho2122** [comment]
It worked. Thank you very much :)

**Comment by cgohlke** [comment]
Roifile >= 2022.9.19 handles integer coordinates in the range `-5000..60536` in accordance with ImageJ. `ImagejRoi.frompoints` adds subpixel coordinates if integer coordinates exceed that range.
