### ISSUE TITLE
Rewriting roi coordinates

### ISSUE THREAD

**Issue by ViriatoII** [cgohlke/roifile#8]
Hey,

I've had the necessity of correcting roi coordinates and I did it like this: 

```
    # Replace roi coordinates by new ones 
    int_diff = np.array([*map(min, new_coordinates.T)])[:,None] 
    roi1.__dict__['integer_coordinates']  = (new_coordinates.T - int_diff ).round().astype(int)
    roi1.__dict__['subpixel_coordinates'] = new_coordinates.T.round().astype(float) 
```

When I print the roi1.coordinates(), I get the new_coordinates as I intend

> Cell408_3717_1346
> [[3773. 1367.]
>  [3785. 1348.]
>  [3763. 1315.]
>  [3743. 1303.]
>  [3733. 1298.]
>  [3720. 1294.]
>  [3699. 1312.]
>  [3671. 1346.]
>  [3668. 1352.]
>  [3659. 1360.]
>  [3661. 1370.]
>  [3659. 1375.]
>  [3662. 1380.]
>  [3664. 1381.]
>  [3673. 1389.]
>  [3682. 1391.]
>  [3687. 1388.]
>  [3690. 1389.]
>  [3711. 1390.]
>  [3754. 1374.]
>  [3762. 1373.]
>  [3764. 1370.]
>  [3773. 1367.]]

However, when I save the roifile ( with `roifile.roiwrite('roifile.zip', list_several_output_rois)`) and then read that roifile.zip file in python or load it into imageJ, the roi.coordinates() result of the exact same roi looks like this:
> Cell408_3717_1346
> [[3773. 3682.]
>  [3785. 3687.]
>  [3763. 3690.]
>  [3743. 3711.]
>  [3733. 3754.]
>  [3720. 3762.]
>  [3699. 3764.]
>  [3671. 3773.]
>  [3668. 1367.]
>  [3659. 1348.]
>  [3661. 1315.]
>  [3659. 1303.]
>  [3662. 1298.]
>  [3664. 1294.]
>  [3673. 1312.]]

It colapses the points and moves some of the missing points x coordinates into the y coordinate of previous points. Can you help me solve this issue? Is it a bug of roifile.roiwrite() ? 

Kind regards,
Ricardo

**Comment by cgohlke** [comment]
The coordinate arrays need to be of shape `(n_coordinates, 2)` in C order. Make sure the `n_coordinates`, `left`, `right`, `top`, and `bottom` attributes are in sync, similar to

https://github.com/cgohlke/roifile/blob/1f765983d1b8907a1bf08cc41cdedaa56b1b2d29/roifile/roifile.py#L423-L429

If that does not help, please provide a complete, minimal, reproducible example to reproduce the issue. 

Not sure I follow the provided code. Why `map`, `[:,None]`, `.__dict__[]`, `int`, `float`?

It's probably a good idea to add verification of the coordinate array shapes to roifile before writing...

**Comment by ViriatoII** [comment]
Thank you, that solves the problem! 

The "map" line was a less smart way of getting the left_top minimum numbers. I now do it like this and it works:


```
    left_top     = cell_coords.min(axis=0)
    right_bottom = cell_coords.max(axis=0)

    roi1.subpixel_coordinates = cell_coords.round().astype(float) 
    roi1.integer_coordinates = (cell_coords - left_top).round().astype(int)
    roi1.n_coordinates = len(roi1.integer_coordinates)
    roi1.left   = int(left_top[0])
    roi1.top    = int(left_top[1])
    roi1.right  = int(right_bottom[0])
    roi1.bottom = int(right_bottom[1])
```

Appreciate the help,
Ricardo
