### ISSUE TITLE
`roiwrite` burns generators

### ISSUE THREAD

**Issue by vreuter** [cgohlke/roifile#9]
Thanks @cgohlke for this great library!

It seems like `roiwrite` burns the ROIs iterable to write if that iterable is a generator-like object / traversable-once, resulting in an empty output file. Would you consider changing implementation to accommodate generator as the argument for ROIs?

**Comment by cgohlke** [comment]
Thanks for reporting the issue. Should be fixed in v2024.3.20.

**Comment by vreuter** [comment]
Awesome, thanks @cgohlke 🙌
